#ifndef _TECHNIQUE_HANDLES_VALIDATION_H_
#define _TECHNIQUE_HANDLES_VALIDATION_H_

#include "Techniques_Def.h"

DECLARE_TECHNIQUE(OpenProcess);
DECLARE_TECHNIQUE(CreateFile);
DECLARE_TECHNIQUE(CloseHandle);
DECLARE_TECHNIQUE(LoadLibrary);
DECLARE_TECHNIQUE(NtQueryObject);

#endif // _TECHNIQUE_HANDLES_VALIDATION_H_
